---
abstract: 'Scriptogr.am API'
author:
  - 'Steve Huff <shuff@cpan.org>'
build_requires:
  Test::More: 0
  Test::Perl::Critic: 0
  Test::Pod: 1.14
  Test::Pod::Coverage: 1.04
configure_requires:
  Module::Build: 0.4
dynamic_config: 1
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Scriptogram
provides:
  WebService::Scriptogram:
    file: lib/WebService/Scriptogram.pm
    version: v0.0.1
requires:
  Params::Validate: 0
  Readonly: 0
  WebService::Simple: 0
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=WebService-Scriptogram
  homepage: https://github.com/hakamadare/webservice-scriptogram
  license: http://dev.perl.org/licenses/
  repository: git://github.com/hakamadare/webservice-scriptogram.git
version: v0.0.1
